# CodeBuild buildspec file for creating container images for a workflow tool
# assumes the following environment variables:
# - PROJECT_BRANCH: git branch / tag / commit-id to build
# - PROJECT_PATH: path in the source to navigate to prior to build
# - REGISTRY: docker image registry (e.g. ECR) to push the container image to
# - CONTAINER_NAME: name of the container
# - AWS_REGION: (Provided by CodeBuild) region to use for ECR
version: 0.2
phases:
  pre_build:
    commands:
      - git checkout $PROJECT_BRANCH
      - cd $PROJECT_PATH
      - cp -R ../_common .
  build:
    commands:
      - echo "Building container"
      - chmod +x _common/build.sh
      - _common/build.sh ${CONTAINER_NAME}
  post_build:
    commands:
      - echo "Tagging container image for ECR"
      - docker tag ${CONTAINER_NAME} ${REGISTRY}/${CONTAINER_NAME}
      - echo "Docker Login to ECR"
      - $(aws ecr get-login --no-include-email --region ${AWS_REGION})
      - echo "Pushing container images to ECR"
      - docker push ${REGISTRY}/${CONTAINER_NAME}