site_name: Genomics Workflows on AWS
nav:
  - Overview: index.md
  - Getting Started:
    - Setup AWS Batch: aws-batch/configure-aws-batch-start.md
    - Creating a custom AMI: aws-batch/create-custom-ami.md
    - Launch the CloudFormation stacks: aws-batch/configure-aws-batch-cfn.md
    - Notes on Amazon VPC: aws-batch/notes-vpc.md
  - Workflow Orchestration:
    - Introduction: orchestration/genomics-workflows-intro.md
    - AWS Step Functions:
      - Introduction and requirements: orchestration/step-functions/intro-step-functions.md
      - Creating a job management container: orchestration/step-functions/create-batchjobrunner-container.md
      # - An example workflow: orchestration/step-functions/create-example-sfl-workflow.md
    - Cromwell:
      - Overview: orchestration/cromwell/cromwell-aws-batch.md
      - Examples: orchestration/cromwell/cromwell-examples.md
  # - Nextflow: orchestration/nextflow/nextflow-aws-batch.md
extra_css: [extra.css]
theme: 
  name: material
  logo: 'images/AWS_logo_RGB_REV.svg'
  palette:
    primary: blue grey
    accent: deep orange
markdown_extensions:
  - fontawesome_markdown
  - admonition
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png

# repo_url: https://github.com/aws-samples/aws-batch-genomics/
# repo_name: Genomics Workflows on AWS
# site_author: Angel Pizarro <pizarroa@amazon.com>
copyright: 2018 Amazon Web Services

plugins:
- search
- macros

extra:
  staging: develop
  develop:
    s3: 
      bucket: aws-genomics-workflows
  production:
    s3:
      bucket: docs.opendata.aws
      prefix: genomics-workflows