site_name: AWS for Genomics Workflows
pages:
  - Home: index.md
  - Setting up AWS Batch:
    - Getting Started: aws-batch/configure-aws-batch-start.md
    - Creating a custom AMI: aws-batch/create-custom-ami.md
    - Configuring AWS Batch with CloudFormation:
      - Launch the CloudFormation stacks: aws-batch/configure-aws-batch-cfn.md
      - Notes on Amazon VPC: aws-batch/notes-vpc.md
  - Setting up a genomics workflow environment:
    - Introduction: genomics-workflows-intro.md
    - AWS Step Functions:
      - Introduction and requirements: step-functions/intro-step-functions.md
      - Creating a job management container: step-functions/create-batchjobrunner-container.md
      # - An example workflow: step-functions/create-example-sfl-workflow.md
    # - Cromwell: cromwell/cromwell-aws-batch.md
    # - Nextflow: nextflow/nextflow-aws-batch.md
theme: readthedocs
markdown_extensions:
  - fontawesome_markdown
  - admonition
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png

# repo_url: https://github.com/aws-samples/aws-batch-genomics/
# repo_name: Genomics Workflows on AWS
# site_author: Angel Pizarro <pizarroa@amazon.com>
copyright: 2018 Amazon Web Services

plugins:
- search
- macros

extra:
  staging: develop
  develop:
    s3: 
      bucket: aws-genomics-workflows
  production:
    s3:
      bucket: docs.opendata.aws
      prefix: genomics-workflows