AWSTemplateFormatVersion: 2010-09-09
Description: >-
  (WWPS-GLS-WF-BATCH) Deploys resource for a AWS Batch environment that is 
  suitable for genomics, including default and high-priority JobQueues.


Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "AWS Batch Environment Config"
        Parameters:
        - LaunchTemplateId
        - VpcId
        - SubnetIds
        - DefaultCEMinvCpus
        - DefaultCEMaxvCpus
        - HighPriorityCEMinvCpus
        - HighPriorityCEMaxvCpus
        - BatchServiceRoleArn
        - Ec2InstanceProfileArn
        - SpotFleetRoleArn
    ParameterLabels:
      LaunchTemplateId:
        default: Launch Template ID
      VpcId:
        default: VPC ID
      SubnetIds:
        default: VPC Subnet IDs
      DefaultCEMinvCpus:
        default: Default Queue Min vCPU count
      DefaultCEMaxvCpus:
        default: Default Queue Max vCPU count
      HighPriorityCEMinvCpus:
        default: HighPriority Queue Min vCPU count
      HighPriorityCEMaxvCpus:
        default: HighPriority Queue Max vCPU count
      BatchServiceRoleArn:
        default: AWS Batch service role ARN
      Ec2InstanceProfileArn:
        default: EC2 Instance Profile ARN
      SpotFleetRoleArn:
        default: Spot Fleet Role ARN


Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: 'The VPC to create security groups and deploy AWS Batch to. NOTE: Must be the same VPC as the provided subnet IDs.'
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: 'Subnets you want your batch compute environment to launch in. We recommend private subnets. NOTE: Must be from the VPC provided.'
  LaunchTemplateId:
    Type: String
    Description: Launch Template you want your AWS Batch Compute Environments to use
  HighPriorityCEMinvCpus:
    Type: Number
    Description: Minimum number of CPUs in the high-priority compute environment. Default 0.
    Default: 0
    MinValue: 0
  HighPriorityCEMaxvCpus:
    Type: Number
    Description: Maximum number of CPUs in the high-priority compute environment. Should be >= than MinCpus
    Default: 100
    MinValue: 0
  DefaultCEMinvCpus:
    Type: Number
    Description: Minimum number of CPUs in the default compute environment. Default 0.
    Default: 0
    MinValue: 0
  DefaultCEMaxvCpus:
    Type: Number
    Description: Maximum number of CPUs in the default compute environment. Should be >= than MinCpus
    Default: 100
    MinValue: 0
  BatchServiceRoleArn:
    Type: String
    Description: The IAM Role ARN for the Batch service
  SpotFleetRoleArn:
    Type: String
    Description: The IAM Role ARN for Batch to call Spot Fleet service
  Ec2InstanceProfileArn:
    Type: String
    Description: The IAM Role ARN for the Batch service


Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SG for genomics workflows on Batch
      VpcId:
        Ref: VpcId
  SGSSHIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref SecurityGroup
      IpProtocol: tcp
      FromPort: 22
      ToPort: 22
      CidrIp: 0.0.0.0/0
  SGAllTcpEgress:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !Ref SecurityGroup
      IpProtocol: tcp
      FromPort: 0
      ToPort: 65535
      CidrIp: 0.0.0.0/0
  SGAllTcpSelfIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref SecurityGroup
      IpProtocol: tcp
      FromPort: 0
      ToPort: 65535
      SourceSecurityGroupId: !Ref SecurityGroup

  SpotComputeEnv:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      ComputeEnvironmentName: !Sub 
       - spot-${StackGuid}
       - StackGuid: !Select [ 2, !Split [ "/", !Ref "AWS::StackId" ]]
      ServiceRole: !Ref BatchServiceRoleArn
      Type: MANAGED
      State: ENABLED
      ComputeResources:
        AllocationStrategy: SPOT_CAPACITY_OPTIMIZED
        # Set the Spot price to 100% of on-demand price
        # This is the maximum price for spot instances that Batch will launch.
        # Lowering this puts a limit on the spot capacity that Batch has available.
        # Spot instances are terminated when on-demand capacity is needed, regardless of the price set.
        BidPercentage: 100 
        # Ec2KeyPair: !Ref Ec2KeyPairName
        LaunchTemplate:
          LaunchTemplateId: !Ref LaunchTemplateId
          Version: $Latest
        InstanceRole: !Ref Ec2InstanceProfileArn
        InstanceTypes:
          - optimal
        MinvCpus: !Ref DefaultCEMinvCpus
        MaxvCpus: !Ref DefaultCEMaxvCpus
        SecurityGroupIds:
          - !Ref SecurityGroup
        SpotIamFleetRole: !Ref SpotFleetRoleArn
        Subnets: !Ref SubnetIds
        Type: SPOT
        Tags:
          Name: !Sub
            - batch-spot-worker-${StackGuid}
            - StackGuid: !Select [ 2, !Split [ "/", !Ref "AWS::StackId" ]]

  OnDemandComputeEnv:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      ComputeEnvironmentName: !Sub 
       - ondemand-${StackGuid}
       - StackGuid: !Select [ 2, !Split [ "/", !Ref "AWS::StackId" ]]
      ServiceRole: !Ref BatchServiceRoleArn
      Type: MANAGED
      State: ENABLED
      ComputeResources:
        LaunchTemplate:
          LaunchTemplateId: !Ref LaunchTemplateId
          Version: $Latest
        InstanceRole:  !Ref Ec2InstanceProfileArn
        InstanceTypes:
          - optimal
        MinvCpus: !Ref HighPriorityCEMinvCpus
        MaxvCpus: !Ref HighPriorityCEMaxvCpus
        SecurityGroupIds:
          - !Ref SecurityGroup
        Subnets: !Ref SubnetIds
        Type: EC2
        Tags:
          Name: !Sub
            - batch-ondemand-worker-${StackGuid}
            - StackGuid: !Select [ 2, !Split [ "/", !Ref "AWS::StackId" ]]

  PriorityQueue:
    Type: AWS::Batch::JobQueue
    Properties:
      JobQueueName: !Sub
        - highpriority-${StackGuid}
        - StackGuid: !Select [ 2, !Split [ "/", !Ref "AWS::StackId" ]]
      Priority: 1000
      State: ENABLED
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref OnDemandComputeEnv
        - Order: 2
          ComputeEnvironment: !Ref SpotComputeEnv

  DefaultQueue:
    Type: AWS::Batch::JobQueue
    Properties:
      JobQueueName: !Sub
        - default-${StackGuid}
        - StackGuid: !Select [ 2, !Split [ "/", !Ref "AWS::StackId" ]]
      Priority: 1
      State: ENABLED
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref SpotComputeEnv
        - Order: 2
          ComputeEnvironment: !Ref OnDemandComputeEnv

Outputs:
  DefaultJobQueueArn:
    Value: !Ref DefaultQueue
  HighPriorityJobQueueArn:
    Value: !Ref PriorityQueue
