---
AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  (WWPS-GLS-WF-SFN-AIO) Creates the complete set of resources needed to run
  genomics workflows using AWS Step-Functions on AWS Batch, including an example
  WGS secondary analysis workflow using bwa-mem, samtools, and bcftools.

Mappings:
  TagMap:
    default:
      architecture: "genomics-workflows"
      solution: "step-functions"
      tags:
        - Key: "architecture"
          Value: "genomics-workflows"
        - Key: "solution"
          Value: "step-functions"

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Data Storage Configuration"
        Parameters:
          - S3BucketName
          - ExistingBucket
      - Label:
          default: "AWS Batch Configuration"
        Parameters:
          - DefaultCEMinvCpus
          - DefaultCEMaxvCpus
          - PriorityCEMinvCpus
          - PriorityCEMaxvCpus
      - Label:
          default: "Distribution Configuration"
        Parameters:
          - ArtifactBucketName
          - ArtifactBucketPrefix
          - TemplateRootUrl

    ParameterLabels:
      S3BucketName:
        default: S3 Bucket Name
      ExistingBucket:
        default: Existing Bucket?
      DefaultCEMinvCpus:
        default: Default Min vCPU
      DefaultCEMaxvCpus:
        default: Default Max vCPU
      PriorityCEMinvCpus:
        default: High Priority Min vCPU
      PriorityCEMaxvCpus:
        default: High Priority Max vCPU
      TemplateRootUrl:
        default: Template Root URL

# Parameters
Parameters:    
  S3BucketName:
    Description: >-
      A S3 bucket name for storing analysis results.
      The bucket name must respect the S3 bucket naming conventions 
      (can contain lowercase letters, numbers, periods and hyphens).
      If left blank a unique bucket name will be generated.
    Type: String
    AllowedPattern: "((?=^.{3,63}$)(?!^(\\d+\\.)+\\d+$)(^(([a-z0-9]|[a-z0-9][a-z0-9\\-]*[a-z0-9])\\.)*([a-z0-9]|[a-z0-9][a-z0-9\\-]*[a-z0-9])$)|(^.{0}$))"
    ConstraintDescription: "Must respect S3 bucket naming conventions"
  ExistingBucket:
    Description: Does this bucket already exist?
    Type: String
    AllowedValues:
      - Yes
      - No
    Default: No
  DefaultCEMinvCpus:
    Description: The minimum number of CPUs for the default Batch Compute Environment
    Type: Number
    Default: 0
  DefaultCEMaxvCpus:
    Description: The maximum number of CPUs for the default Batch Compute Environment
    Type: Number
    Default: 100
  PriorityCEMinvCpus:
    Description: The minimum number of CPUs for the high-priority Batch Compute Environment
    Type: Number
    Default: 0
  PriorityCEMaxvCpus:
    Description: The maximum number of CPUs for the high-priority Batch Compute Environment
    Type: Number
    Default: 100  
  ArtifactBucketName:
    Type: String
    Default: aws-genomics-workflows
    Description: >-
      S3 Bucket where artifacts and additions scripts are stored
  ArtifactBucketPrefix:
    Type: String
    Default: artifacts
    Description: >-
      Prefix in ArtifactBucketName where artifacts and additions scripts are stored
  
  TemplateRootUrl:
    Type: String
    Description: >-
      Root URL for where nested templates are stored
    Default: https://aws-genomics-workflows.s3.amazonaws.com/templates
    ConstraintDescription: >-
      Must be a valid S3 HTTP URL
    AllowedPattern: "https://[a-z0-9-./]{0,}s3(-[a-z0-9]+)*\\.amazonaws\\.com/[a-z0-9-./]{3,}"


Resources:
  VpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:  https://aws-quickstart.s3.amazonaws.com/quickstart-aws-vpc/templates/aws-vpc.template
      TimeoutInMinutes: 15
      Parameters:
        AvailabilityZones:
          Fn::Join:
            - "," 
            - - !Sub "${AWS::Region}a"
              - !Sub "${AWS::Region}b"
        NumberOfAZs: "2"
      Tags: !FindInMap ["TagMap", "default", "tags"]

  GWFCoreStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:  !Sub ${TemplateRootUrl}/gwfcore/gwfcore-root.template.yaml
      Parameters:
        Namespace: !Sub ${AWS::StackName}
        VpcId: !GetAtt 'VpcStack.Outputs.VPCID'
        SubnetIds: !Sub "${VpcStack.Outputs.PrivateSubnet1AID}, ${VpcStack.Outputs.PrivateSubnet2AID}"
        S3BucketName: !Ref S3BucketName
        ExistingBucket: !Ref ExistingBucket
        DefaultCEMinvCpus: !Ref 'DefaultCEMinvCpus'
        DefaultCEMaxvCpus: !Ref 'DefaultCEMaxvCpus'
        PriorityCEMinvCpus: !Ref 'PriorityCEMinvCpus'
        PriorityCEMaxvCpus: !Ref 'PriorityCEMaxvCpus'
        ArtifactBucketName: !Ref ArtifactBucketName
        ArtifactBucketPrefix: !Ref ArtifactBucketPrefix
        TemplateRootUrl: !Ref TemplateRootUrl
      Tags: !FindInMap ["TagMap", "default", "tags"]

  SfnStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${TemplateRootUrl}/step-functions/sfn-resources.template.yaml
      Parameters:
        Namespace: !Sub ${AWS::StackName}
        # possibly autogenerated s3 bucket name
        S3BucketName: !GetAtt 'GWFCoreStack.Outputs.S3Bucket'
        BatchJobQueue: !GetAtt 'GWFCoreStack.Outputs.DefaultJobQueueArn'
        ArtifactBucketName: !Ref ArtifactBucketName
        ArtifactBucketPrefix: !Ref ArtifactBucketPrefix
        TemplateRootUrl: !Ref TemplateRootUrl
      Tags: !FindInMap ["TagMap", "default", "tags"]


Outputs:
  StateMachine:
    Value: !GetAtt 'SfnStack.Outputs.StateMachine'
    Export:
      Name: !Sub ${AWS::StackName}-StateMachine
    Description: >-
      Example AWS Step Functions state machine
  StateMachineInput:
    Value: !GetAtt 'SfnStack.Outputs.StateMachineInput'
    Description: >-
      Example input for the state machine.  Use this when executing your workflow.
  VpcId:
    Description: >-
      The VPC created for your Nextflow stack.
    Value: !GetAtt 'VpcStack.Outputs.VPCID'
  S3Bucket:
    Value: !GetAtt 'GWFCoreStack.Outputs.S3Bucket'
    Export:
      Name: !Sub ${AWS::StackName}-S3Bucket
    Description: >-
      S3 bucket for storing genomics workflow input and output data
  BatchDefaultQueue:
    Value: !GetAtt 'GWFCoreStack.Outputs.DefaultJobQueueArn'
    Export:
      Name: !Sub ${AWS::StackName}-DefaultJobQueue
    Description: >-
      The default AWS Batch job queue for workflow jobs, based on EC2 SPOT instances
  BatchPriorityQueue:
    Value: !GetAtt 'GWFCoreStack.Outputs.PriorityJobQueueArn'
    Export:
      Name: !Sub ${AWS::StackName}-HighPrioirityJobQueue
    Description: >-
      AWS Batch job queue for high priority workflow jobs, based on EC2 On-Demand
      instances

...