---
AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  (WWPS-GLS-WF-NEXTFLOW-AIO) Creates the complete set of resources needed to run
  genomics workflows using Nextflow on AWS Batch


Mappings:
  TagMap:
    default:
      architecture: "genomics-workflows"
      solution: "nextflow"
      tags:
        - Key: "architecture"
          Value: "genomics-workflows"
        - Key: "solution"
          Value: "nextflow"


Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Data Storage Configuration"
        Parameters:
          - S3DataBucketName
          - ExistingDataBucket
      - Label:
          default: "AWS Batch Configuration"
        Parameters:
          - DefaultCEMinvCpus
          - DefaultCEMaxvCpus
          - PriorityCEMinvCpus
          - PriorityCEMaxvCpus
      - Label:
          default: "Nextflow Configuration"
        Parameters:
          - NextflowVersion
          - NextflowVersionSpecified
          - S3NextflowBucketName
          - ExistingNextflowBucket
      - Label:
          default: "Distribution Configuration"
        Parameters:
          - ArtifactBucketName
          - ArtifactBucketPrefix
          - TemplateRootUrl

    ParameterLabels:
      NextflowVersion:
        default: Nextflow Version
      NextflowVersionSpecified:
        default: Nextflow Version Specified
      S3DataBucketName:
        default: S3 Data Bucket Name
      ExistingDataBucket:
        default: Existing Data Bucket?
      S3NextflowBucketName:
        default: S3 Nextflow Bucket Name
      ExistingNextflowBucket:
        default: Existing Nextflow Bucket?
      DefaultCEMinvCpus:
        default: Default Min vCPU
      DefaultCEMaxvCpus:
        default: Default Max vCPU
      PriorityCEMinvCpus:
        default: High Priority Min vCPU
      PriorityCEMaxvCpus:
        default: High Priority Max vCPU
      TemplateRootUrl:
        default: Template Root URL


Parameters:
  S3DataBucketName:
    Description: >-
      A S3 bucket name for storing analysis results
      The bucket name must respect the S3 bucket naming conventions 
      (can contain lowercase letters, numbers, periods and hyphens).
      If left blank a unique bucket name will be generated.

    Type: String
    Default: ""
    AllowedPattern: "((?=^.{3,63}$)(?!^(\\d+\\.)+\\d+$)(^(([a-z0-9]|[a-z0-9][a-z0-9\\-]*[a-z0-9])\\.)*([a-z0-9]|[a-z0-9][a-z0-9\\-]*[a-z0-9])$)|(^.{0}$))"
    ConstraintDescription: "Must respect S3 bucket naming conventions"

  ExistingDataBucket:
    Description: Does this bucket already exist?
    Type: String
    AllowedValues:
      - Yes
      - No
    Default: No
  DefaultCEMinvCpus:
    Description: The minimum number of CPUs for the default Batch Compute Environment
    Type: Number
    Default: 0
  DefaultCEMaxvCpus:
    Description: The maximum number of CPUs for the default Batch Compute Environment
    Type: Number
    Default: 100
  PriorityCEMinvCpus:
    Description: The minimum number of CPUs for the high-priority Batch Compute Environment
    Type: Number
    Default: 0
  PriorityCEMaxvCpus:
    Description: The maximum number of CPUs for the high-priority Batch Compute Environment
    Type: Number
    Default: 100
  
  S3NextflowBucketName:
    Type: String
    Default: ""
    Description: >-
      (Optional) S3 Bucket used to store Nextflow metadata (session cache, logs, and intermediate results).
      Defaults to the S3 Bucket used for data.
    AllowedPattern: "(^$|(?=^.{3,63}$)(?!^(\\d+\\.)+\\d+$)(^(([a-z0-9]|[a-z0-9][a-z0-9\\-]*[a-z0-9])\\.)*([a-z0-9]|[a-z0-9][a-z0-9\\-]*[a-z0-9])$))"
    ConstraintDescription: "Must respect S3 bucket naming conventions"
      
  ExistingNextflowBucket:
    Type: String
    Description: >-
      Does the Nextflow S3 Bucket already exist?  If not, it will be created.
    AllowedValues:
      - Yes
      - No
    Default: No
  
  NextflowVersion:
    Type: String
    Default: latest
    AllowedValues:
      - latest
      - specify ...
    Description: >-
      Version of Nextflow to use. Select "specify ..." to provide a specific version.
  
  NextflowVersionSpecified:
    Type: String
    Description: >-
      Specific version of Nextflow to use. Must match a released version number - e.g. "20.04.1".
  
  ArtifactBucketName:
    Type: String
    Default: aws-genomics-workflows
    Description: >-
      S3 Bucket where artifacts and additions scripts are stored
  ArtifactBucketPrefix:
    Type: String
    Default: artifacts
    Description: >-
      Prefix in ArtifactBucketName where artifacts and additions scripts are stored

  TemplateRootUrl:
    Type: String
    Description: >-
      Root URL for where nested templates are stored
    Default: https://aws-genomics-workflows.s3.amazonaws.com/templates
    ConstraintDescription: >-
      Must be a valid S3 HTTP URL
    AllowedPattern: "https://[a-z0-9-./]{0,}s3(-[a-z0-9]+)*\\.amazonaws\\.com/[a-z0-9-./]{3,}"


Conditions:
  UseOneBucket:
    Fn::Or:
      - !Equals [!Ref S3NextflowBucketName, ""]
      - !Equals [!Ref S3NextflowBucketName, !Ref S3DataBucketName]


Resources:
  VpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:  https://aws-quickstart.s3.amazonaws.com/quickstart-aws-vpc/templates/aws-vpc.template
      TimeoutInMinutes: 15
      Parameters:
        AvailabilityZones:
          Fn::Join:
            - "," 
            - - !Sub "${AWS::Region}a"
              - !Sub "${AWS::Region}b"
        NumberOfAZs: "2"
      Tags: !FindInMap ["TagMap", "default", "tags"]

  GWFCoreStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:  !Sub ${TemplateRootUrl}/gwfcore/gwfcore-root.template.yaml
      Parameters:
        Namespace: !Sub ${AWS::StackName}
        VpcId: !GetAtt 'VpcStack.Outputs.VPCID'
        SubnetIds: !Sub "${VpcStack.Outputs.PrivateSubnet1AID}, ${VpcStack.Outputs.PrivateSubnet2AID}"
        S3BucketName: !Ref S3DataBucketName
        ExistingBucket: !Ref ExistingDataBucket
        DefaultCEMinvCpus: !Ref 'DefaultCEMinvCpus'
        DefaultCEMaxvCpus: !Ref 'DefaultCEMaxvCpus'
        PriorityCEMinvCpus: !Ref 'PriorityCEMinvCpus'
        PriorityCEMaxvCpus: !Ref 'PriorityCEMaxvCpus'
        ArtifactBucketName: !Ref ArtifactBucketName  # should reference upstream distribution
        ArtifactBucketPrefix: !Ref ArtifactBucketPrefix  # should reference upstream distribution
        TemplateRootUrl: !Ref TemplateRootUrl
      Tags: !FindInMap ["TagMap", "default", "tags"]

  NextflowStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:  !Sub ${TemplateRootUrl}/nextflow/nextflow-resources.template.yaml
      Parameters:
        Namespace: !Sub ${AWS::StackName}
        GWFCoreNamespace: !Sub ${AWS::StackName}
        # possibly autogenerated bucket name
        S3DataBucketName: !GetAtt GWFCoreStack.Outputs.S3Bucket
        S3NextflowBucketName:
          Fn::If:
            - UseOneBucket
            # possibly autogenerated bucket name
            - !GetAtt GWFCoreStack.Outputs.S3Bucket
            - !Ref S3NextflowBucketName
        ExistingBucket: 
          Fn::If:
            - UseOneBucket
            - True  # by the time this stack is created, the data bucket should exist
            - !Ref ExistingNextflowBucket
        NextflowVersion: !Ref NextflowVersion
        NextflowVersionSpecified: !Ref NextflowVersionSpecified
        TemplateRootUrl: !Ref TemplateRootUrl
      Tags: !FindInMap ["TagMap", "default", "tags"]


Outputs:
  NextflowContainerImage:
    Value: !GetAtt NextflowStack.Outputs.NextflowContainerImage
    Export:
      Name: !Sub "${AWS::StackName}-NextflowContainerImage"
    
  NextflowJobDefinition:
    Value: !GetAtt NextflowStack.Outputs.NextflowJobDefinition
    Export:
      Name: !Sub "${AWS::StackName}-NextflowJobDefinition"
    Description: >-
      Batch Job Definition that creates a nextflow head node for running workflows
  
  S3NextFlowBucket:
    Value: !GetAtt NextflowStack.Outputs.NextflowBucket
    Export:
      Name: !Sub "${AWS::StackName}-NextflowBucket"
    Description: >-
      S3 Bucket used to store Nextflow metadata (session cache, logs, and intermediate results)
  S3NextflowLogsDir:
    Value: !GetAtt NextflowStack.Outputs.LogsDir
    Export:
      Name: !Sub "${AWS::StackName}-NextflowLogsDir"
    Description: >-
      S3 URI where nextflow session cache and logs are stored.
  S3NextflowWorkDir:
    Value: !GetAtt NextflowStack.Outputs.WorkDir
    Export:
      Name: !Sub "${AWS::StackName}-NextflowWorkDir"
    Description: >-
      S3 URI where workflow intermediate results are stored.
  
  VpcId:
    Description: >-
      The VPC created for your Nextflow stack.
    Value: !GetAtt 'VpcStack.Outputs.VPCID'
  S3DataBucket:
    Value: !GetAtt 'GWFCoreStack.Outputs.S3Bucket'
    Export:
      Name: !Sub "${AWS::StackName}-DataBucket"
    Description: >-
      S3 bucket for storing genomics workflow input and output data
  BatchDefaultQueue:
    Value: !GetAtt 'GWFCoreStack.Outputs.DefaultJobQueueArn'
    Export:
      Name: !Sub "${AWS::StackName}-DefaultJobQueue"
    Description: >-
      The default AWS Batch job queue for workflow jobs, based on EC2 SPOT instances
  BatchPriorityQueue:
    Value: !GetAtt 'GWFCoreStack.Outputs.PriorityJobQueueArn'
    Export:
      Name: !Sub "${AWS::StackName}-PriorityJobQueue"
    Description: >-
      AWS Batch job queue for high priority workflow jobs, based on EC2 On-Demand
      instances
...