AWSTemplateFormatVersion: 2010-09-09
Description: Creates a set of IAM Roles and EC2 Instance Profiles to use with Cromwell and AWS Batch
Resources:
  CromwellEc2InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        PolicyName: !Sub Cromwell-Autoscale-EBS-${AWS::Region}
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            Effect: Allow
            Action:
              - "ec2:createVolume"
              - "ec2:attacheVolume"
              - "ec2:modifyInstanceAttribute"
              - "ec2:describeVolumes"
      ManagedPolicyArns:
      - "arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role"
  CromwellEc2InstanceProfile:
  CromwellEcsRole:
  CromwellSpotFleetRole:
  CromwellBatchServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: batch.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSBatchServiceRole
